version: "3.9"

services:
  postgres:
    container_name: next_postgres
    image: postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
